rvm:
  - 2.2.3
before_script:
  - psql -c "CREATE USER workshops WITH PASSWORD 'workshops';" -U postgres
  - psql -c 'create database workshops_test;' -U postgres
  - psql -c "ALTER DATABASE workshops_test OWNER TO workshops;" -U postgres
  - psql -c "ALTER USER workshops CREATEDB;" -U postgres
addons:
  postgresql: '9.3'
